# Generated by Django 4.1.7 on 2023-04-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddSocialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gmail', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('probability', models.CharField(choices=[('YES', 'YES'), ('MAYBE', 'MAYBE'), ('NO', 'NO')], max_length=20)),
                ('ExcelModel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('userid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
                ('task', models.CharField(blank=True, max_length=500, null=True)),
                ('assignedto', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OnProgress', 'OnProgress'), ('Completed', 'Completed')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardiansname', models.CharField(blank=True, max_length=200, null=True)),
                ('houseno', models.CharField(blank=True, max_length=200, null=True)),
                ('housename', models.CharField(blank=True, max_length=200, null=True)),
                ('genderage', models.CharField(blank=True, max_length=200, null=True)),
                ('idno', models.CharField(blank=True, max_length=200, null=True)),
                ('District_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Localbody_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Ward_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Pollingstation_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
                ('datereceived', models.DateTimeField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=500, null=True)),
                ('reply', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalbodyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Localbody_name', models.CharField(blank=True, max_length=200, null=True)),
                ('District_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.districtmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('idno', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProbabilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReportIssueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
                ('privilege', models.CharField(blank=True, max_length=200, null=True)),
                ('issue', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
                ('privilege', models.CharField(blank=True, max_length=200, null=True)),
                ('datereceived', models.DateTimeField(blank=True, null=True)),
                ('suggestion', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
                ('issue', models.CharField(blank=True, max_length=500, null=True)),
                ('reply', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('choice', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=50)),
                ('assigned', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('idno', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('privilege', models.CharField(choices=[('LocalMember', 'LocalMember'), ('CounsilMember', 'CounsilMember'), ('SuperMember', 'SuperMember'), ('President', 'President')], max_length=80)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('localbody', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(max_length=20)),
                ('verify_user', models.CharField(choices=[('Verified', 'Verified')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VoterAddModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('guardian', models.CharField(max_length=200)),
                ('houseno', models.CharField(max_length=20)),
                ('housename', models.CharField(max_length=80)),
                ('genderage', models.CharField(max_length=40)),
                ('idcard', models.IntegerField()),
                ('district', models.CharField(max_length=80)),
                ('localbody', models.CharField(max_length=80)),
                ('ward', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='WardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ward_name', models.CharField(blank=True, max_length=200, null=True)),
                ('District_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.districtmodel')),
                ('Localbody_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.localbodymodel')),
            ],
        ),
        migrations.CreateModel(
            name='PollingstationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pollingstation_name', models.CharField(blank=True, max_length=200, null=True)),
                ('District_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.districtmodel')),
                ('Localbody_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.localbodymodel')),
                ('Ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.wardmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('comments', models.CharField(max_length=500)),
                ('serialno', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardiansname', models.CharField(blank=True, max_length=200, null=True)),
                ('houseno', models.CharField(blank=True, max_length=200, null=True)),
                ('housename', models.CharField(blank=True, max_length=200, null=True)),
                ('genderage', models.CharField(blank=True, max_length=200, null=True)),
                ('idno', models.CharField(blank=True, max_length=200, null=True)),
                ('userassigned', models.CharField(blank=True, max_length=200, null=True)),
                ('Pollingstation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.pollingstationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_user', models.BooleanField(default=False)),
                ('problems_reply', models.CharField(blank=True, max_length=500, null=True)),
                ('userregister_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.userregistermodel')),
            ],
        ),
    ]
