# Generated by Django 4.1.7 on 2023-04-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='Pollingstation_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
