# Generated by Django 4.1.7 on 2023-04-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionapp', '0004_presidentmodel_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidentmodel',
            name='status',
            field=models.CharField(choices=[('OnProgress', 'OnProgress'), ('Completed', 'Completed')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
