from django.urls import path
from .views import *

urlpatterns = [

    path('', index),
    path('about/', about),
    path('contact/', contact),
    path('service/', service),
    path('signup/', UserRegister, name="signup"),
    path('login/', UserLogin),
    path('userdisplay/', UserDisplay),
    path('userupdate/<int:id>', UserUpdate),
    path('userdelete/<int:id>', UserDelete),
    path('verifyusers/<int:id>', VerifyUser),
    path('verifiedusers/', VerifiedUsers),
    path('adminhome/', AdminView),
    path('localhome/', LocalMemberHome, name="localhome"),
    path('Counsilhome/', CounsilMemberHome, name="Counsilhome"),
    path('Superhome/', SuperMemberHome, name="Superhome"),
    path('adminsuccess/', AdminSuccess, name="adminsuccess"),
    path('lmsuccess/', LMSuccess, name="lmsuccess"),
    path('cmsuccess/', CMSuccess, name="cmsuccess"),
    path('smsuccess/', SMSuccess, name="smsuccess"),
    path('pmsuccess/', PMSuccess, name="pmsuccess"),
    path('pmdelete/', PMDelete, name="pmdelete"),
    path('replydisplaylm/',IssueReplyDisplayLM, name="replydisplaylm"),
    path('replydisplaycm/',IssueReplyDisplayCM, name="replydisplaycm"),
    path('replydisplaysm/',IssueReplyDisplaySM, name="replydisplaysm"),
    path('replydisplayp/',IssueReplyDisplayP, name="replydisplayp"),

    path('smdistrict/', SuperMemberdistrict,name='smdistrict'),
    path('smlocal/<int:id>', SuperMemberlocalbody,name='smlocal'),
    path('smward/<int:id>/<int:District_id>', SuperMemberward,name='smward'),
    path('smpolling/<int:id>/<int:District_id>/<int:Localbody_id>', SuperMemberpolling,name='smpolling'),
    path('smvoterdisplay/<int:id>',SuperMemberVoters,name="smvoterdisplay"),
    path('smuserdisplay/',SMUsersDisplay,name="smuserdisplay"),
    path('assigntasksm/<int:id>', SMAssignTask,name='assigntasksm'),

    path('Presidenthome/', PresidentHome, name="Presidenthome"),
    path('presidentdistrict/', Presidentdistrictview,name='presidentdistrict'),
    path('presidentlocal/<int:id>', Presidentlocalbodyview,name='presidentlocal'),
    path('presidentward/<int:id>/<int:District_id>', Presidentwardview,name='presidentward'),
    path('presidentpolling/<int:id>/<int:District_id>/<int:Localbody_id>', Presidentpollingview,name='presidentpolling'),
    path('presidentvoterdisplay/<int:id>',PresidentVoterDisplay,name="presidentvoterdisplay"),
    path('presidentuserdisplay/',PresidentUsersDisplay,name="presidentuserdisplay"),
    path('assigntaskpresident/<int:id>', PresidentAssignTask,name='assigntaskpresident'),
    path('presidenttaskdis/',PresidentDisplayTask,name="presidenttaskdis"),
    path('presidenttaskdelete/<int:id>', PresidentTaskDelete,name='presidenttaskdelete'),

    path('pmdistrict/', PMdistrictview,name='pmdistrict'),
    path('pmlocal/<int:id>', PMlocalbodyview,name='pmlocal'),
    path('pmward/<int:id>/<int:District_id>', PMwardview,name='pmward'),
    path('pmpolling/<int:id>/<int:District_id>/<int:Localbody_id>', PMpollingview,name='pmpolling'),
    path('dispresident/<int:id>', PresidentDataDisplay),

    path('PresidentTaskDisplay/',PresidentTaskDisplay,name="PresidentTaskDisplay"),
    path('PresidentTaskUpdate/<int:id>',TaskUpdate,name="PresidentTaskUpdate"),

    path('PresidentTaskDisplayCM/',PresidentTaskDisplayCM,name="PresidentTaskDisplayCM"),
    path('PresidentVoterTaskDisplayCM/',PresidentVoterTaskDisplayCM,name="PresidentVoterTaskDisplayCM"),
    path('PresidentTaskUpdateCM/<int:id>',TaskUpdateCM,name="PresidentTaskUpdateCM"),
    path('PresidentVoterTaskUpdateCM/<int:id>',VoterTaskUpdateCM,name="PresidentVoterTaskUpdateCM"),

    path('signup/', UserRegister),
    # path('voteradd/', VotersAdd),
    path('voterdisplay/<int:id>',VoterDisplay,name="voterdisplay"),
    path('voterdetails/<int:id>', VoterDetails),
    path('displaycounsiler/<int:id>', display),
    path('counsilerdata/', counsilerview),
    path('districtview/', Districtview,name="districtview"),
    path('localbodyview/<int:id>', Localbodyview,name="localbodyview"),
    path('wardview/<int:id>/<int:District_id>', Wardview,name="wardview"),
    path('pollingstationview/<int:id>/<int:District_id>/<int:Localbody_id>', pollingstationview,name="pollingstationview"),
    path('addexceldetails/<int:id>/<int:District_id>/<int:Localbody_id>', addexceldetails,name="addexceldetails"),
    path('excel_import/<int:id>', excel_import,name="excel_import"),
    path('excelview/', excelview,name="excelview"),
    path('counsilercomment/<int:id>', Comment,name="counsilercomment"),
    path('viewvoterdetials/', viewvoterdetials,name="viewvoterdetials"),
    path('admincommentview/', Admincommentview,name='admincommentview'),
    path('adminexcelview/', Adminexcelview,name='adminexcelview'),
    path('admindistrictview/', Admindistrictview,name='admindistrictview'),
    path('adminlocalview/<int:id>', Adminlocalbodyview,name='adminlocalview'),
    path('adminwardview/<int:id>/<int:District_id>', Adminwardview,name='adminwardview'),
    path('adminpollingview/<int:id>/<int:District_id>/<int:Localbody_id>', Adminpollingview,name='adminpollingview'),

    path('admindistrictdisplay/', AdmindistrictDisplay,name='admindistrictdisplay'),
    path('adminlocaldisplay/<int:id>', AdminlocalbodyDisplay,name='adminlocaldisplay'),
    path('adminwarddisplay/<int:id>/<int:District_id>', AdminwardDisplay,name='adminwarddisplay'),
    path('adminpollingdisplay/<int:id>/<int:District_id>/<int:Localbody_id>', AdminpollingDisplay,name='adminpollingdisplay'),
    path('adminvoterdisplay/<int:id>',AdminVoterDisplay,name="adminvoterdisplay"),
    path('districtadd/', AdmindistrictAdd),
    path('districtupdate/<int:id>', AdmindistrictUpdate),
    path('districtdelete/<int:id>', AdmindistrictDelete),
    path('localadd/', AdminlocalbodyAdd),
    path('localupdate/<int:id>', AdminlocalbodyUpdate),
    path('localdelete/<int:id>', AdminlocalbodyDelete),
    path('wardadd/', AdminwardAdd),
    path('wardupdate/<int:id>', AdminwardUpdate),
    path('warddelete/<int:id>', AdminwardDelete),
    path('pollingadd/', AdminpollingAdd),
    path('pollingupdate/<int:id>', AdminpollingUpdate),
    path('pollingdelete/<int:id>', AdminpollingDelete),

    path('reportissue/', IssueReport),
    path('AdminIssueDisplayLM/', AdminIssueDisplayLM, name='AdminIssueDisplayLM'),
    path('AdminIssueDisplayCM/', AdminIssueDisplayCM, name='AdminIssueDisplayCM'),
    path('AdminIssueDisplaySM/', AdminIssueDisplaySM, name='AdminIssueDisplaySM'),
    path('AdminIssueDisplayP/', AdminIssueDisplayP, name='AdminIssueDisplayP'),
    path('issuedisplay/', AdminIssueUsers),
    path('issuereply/<int:id>',AdminIssueReply),
    path('replydisplay/',IssueReplyDisplay),
    path('suggestionsdisplay/',SuggestionDisplay),

    path('addsuggestions/', SuggesstionReport),
    path('localreportissue/', LocalIssueReport),
    path('localaddsuggestions/', LocalSuggesstionReport),
    path('counsilreportissue/', CounsilIssueReport),
    path('counsiladdsuggestions/', CounsilSuggesstionReport),
    path('superreportissue/', SuperIssueReport),
    path('superaddsuggestions/', SuperSuggesstionReport),
    path('presidentreportissue/', PresidentIssueReport),
    path('presidentaddsuggestions/', PresidentSuggesstionReport),

    path('counsilerdistrictview/', Counsilerdistrictview,name='counsilerdistrictview'),
    path('counsilerlocalview/<int:id>', CounsilerLocalbodyview,name='counsilerlocalview'),
    path('counsilerwardview/<int:id>/<int:District_id>', CounsilerWardview,name='counsilerwardview'),
    path('counsilerpollingview/<int:id>/<int:District_id>/<int:Localbody_id>', Counsilerpollingstationview,name='counsilerpollingview'),
    path('counsilermenu/<int:id>',CounsilerVoterDisplay,name="counsilermenu"),

    path('supermemberdistrictview/', Supermemberdistrictview,name='supermemberdistrictview'),
    path('supermemberlocalview/<int:id>', SupermemberLocalview,name='supermemberlocalview'),
    path('supermemberwardview/<int:id>/<int:District_id>', SupermemberWardview,name='supermemberwardview'),
    path('supermemberpollingview/<int:id>/<int:District_id>/<int:Localbody_id>', Supermemberpollview,name='supermemberpollingview'),
    path('supermembermenu/<int:id>',SupermemberVoterDisplay,name="supermembermenu"),

    path('Comments/<int:id>',Supermember),
    path('Superview/<int:id>',SuperView),
    path('presidentcomment/<int:id>',PresidentComment),

    path('count/',Count),
    path('countper/', CountPercentage),
]